version: '3'
services:

  demos-database:
    image: postgres:11.3-alpine
    network_mode: host
    container_name: demos-database
    volumes:
      - /var/lib/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=d3mOz
      - POSTGRES_USER=demos
      - PGDATA=/var/lib/postgresql/data/pgdata

  demos-classifier:
    build:
      context: ..
      dockerfile: ./demos-package/classifier/Dockerfile
    image: benjaminpochat/demos-classifier:0.0.3
    network_mode: host
    container_name: demos-classifier
    ports:
      - 8501:8501
    environment:
      - MODEL_NAME=demos

  demos-core:
    build:
      context: ..
      dockerfile: ./demos-package/core/Dockerfile
    image: benjaminpochat/demos-rest-server:0.0.3
    network_mode: host
    container_name: demos-core
    depends_on:
      - demos-database
    environment:
      - demos.datasource.url=jdbc:postgresql://localhost:5432/demos
      - demos.datasource.user=demos
      - demos.datasource.password=d3m0z

  demos-scraper:
    build:
      context: ..
      dockerfile: ./demos-package/scraper/Dockerfile
    image: benjaminpochat/demos-scraper:0.0.3
    network_mode: host
    container_name: demos-scraper
    command: archive -tfs -n 100
    depends_on:
      - demos-core
      - demos-classifier

  demos-gui:
    build:
      context: ..
      dockerfile: ./demos-package/gui/Dockerfile
    image: benjaminpochat/demos-gui:0.0.3
    network_mode: host
    container_name: demos-gui
    ports:
      - 80:80
    depends_on:
      - demos-core

  demos-message-bus-zookeeper:
    image: wurstmeister/zookeeper
    network_mode: host
    ports:
      - 2181:2181

  demos-message-bus:
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - 9092:9092
    environment:
      KAFKA_CREATE_TOPICS: "UnclassifiedPdfUrl:1:1,UnclassifiedPdfContent:1:1"
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
    network_mode: host
    volumes:
      - /var/lib/kafka:/var/run/docker.sock
    depends_on:
      - demos-message-bus-zookeeper
